//
//  This CSharp output file generated by Gardens Point LEX
//  Gardens Point LEX (GPLEX) is Copyright (c) John Gough, QUT 2006-2014.
//  Output produced by GPLEX is the property of the user.
//  See accompanying file GPLEXcopyright.rtf.
//
//  GPLEX Version:  1.2.2
//  Machine:  ROCKYWIN8
//  DateTime: 2014/8/27 0:28:24
//  UserName: Rocky
//  GPLEX input file <Shaderlab.lex - 2014/8/27 0:28:22>
//  GPLEX frame file <embedded resource>
//
//  Option settings: unicode, verbose, noParser, noFiles, minimize
//  Option settings: classes, compressMap, compressNext, embedbuffers
//

//
// Revised backup code
// Version 1.2.1 of 24-June-2013
//
//
#define BACKUP
#define STANDALONE
#define NOFILES
#define PERSIST

using System;
using System.IO;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Diagnostics.CodeAnalysis;


namespace ShaderlabVS.Lexer
{   
    /// <summary>
    /// Summary Canonical example of GPLEX automaton
    /// </summary>
    
#if STANDALONE
    //
    // These are the dummy declarations for stand-alone GPLEX applications
    // normally these declarations would come from the parser.
    // If you declare /noparser, or %option noparser then you get this.
    //

     public enum Tokens
    { 
      EOF = 0, maxParseToken = int.MaxValue 
      // must have at least these two, values are almost arbitrary
    }

     public abstract class ScanBase
    {
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public abstract int yylex();

        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yywrap")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yywrap")]
        protected virtual bool yywrap() { return true; }

#if BABEL
        protected abstract int CurrentSc { get; set; }
        // EolState is the 32-bit of state data persisted at 
        // the end of each line for Visual Studio colorization.  
        // The default is to return CurrentSc.  You must override
        // this if you want more complicated behavior.
        public virtual int EolState { 
            get { return CurrentSc; }
            set { CurrentSc = value; } 
        }
    }
    
     public interface IColorScan
    {
        void SetSource(string source, int offset);
        int GetNext(ref int state, out int start, out int end);
#endif // BABEL
    }

#endif // STANDALONE
    
    // If the compiler can't find the scanner base class maybe you
    // need to run GPPG with the /gplex option, or GPLEX with /noparser
#if BABEL
     public sealed partial class Scanner : ScanBase, IColorScan
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
        
        protected override int CurrentSc 
        {
             // The current start state is a property
             // to try to avoid the user error of setting
             // scState but forgetting to update the FSA
             // start state "currentStart"
             //
             get { return currentScOrd; }  // i.e. return YY_START;
             set { currentScOrd = value;   // i.e. BEGIN(value);
                   currentStart = startState[value]; }
        }
#else  // BABEL
     public sealed partial class Scanner : ScanBase
    {
        private ScanBuff buffer;
        int currentScOrd;  // start condition ordinal
#endif // BABEL
        
        /// <summary>
        /// The input buffer for this scanner.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ScanBuff Buffer { get { return buffer; } }
        
        private static int GetMaxParseToken() {
     System.Reflection.FieldInfo f = typeof(Tokens).GetField("maxParseToken");
            return (f == null ? int.MaxValue : (int)f.GetValue(null));
        }
        
        static int parserMax = GetMaxParseToken();
        
        enum Result {accept, noMatch, contextFound};

        const int maxAccept = 28;
        const int initial = 29;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;
        const int COMMENT = 1;

#region user code
/**********************************************************************************/
/********************************User Defined Code*********************************/
/**********************************************************************************/
public int NextToken() { return yylex(); }
     public int GetPos() { return yypos; }
     public int GetLength() { return yyleng; }
/********************************Rules Section*********************************/
#endregion user code

        int state;
        int currentStart = startState[0];
        int code;      // last code read
        int cCol;      // column number of code
        int lNum;      // current line number
        //
        // The following instance variables are used, among other
        // things, for constructing the yylloc location objects.
        //
        int tokPos;        // buffer position at start of token
        int tokCol;        // zero-based column number at start of token
        int tokLin;        // line number at start of token
        int tokEPos;       // buffer position at end of token
        int tokECol;       // column number at end of token
        int tokELin;       // line number at end of token
        string tokTxt;     // lazily constructed text of token
#if STACK          
        private Stack<int> scStack = new Stack<int>();
#endif // STACK

#region ScannerTables
    struct Table {
        public int min; public int rng; public int dflt;
        public short[] nxt;
        public Table(int m, int x, int d, short[] n) {
            min = m; rng = x; dflt = d; nxt = n;
        }
    };

    static int[] startState = new int[] {29, 24, 0};

#region CompressedCharacterMap
    //
    // There are 45 equivalence classes
    // There are 2 character sequence regions
    // There are 1 tables, 121 entries
    // There are 1 runs, 0 singletons
    // Decision tree depth is 1
    //
    static sbyte[] mapC0 = new sbyte[121] {
/*     '\0' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 16, 0, 16, 16, 16, 2, 2, 
/*   '\x10' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\x20' */ 16, 2, 14, 38, 2, 2, 2, 2, 2, 2, 3, 9, 2, 10, 11, 1, 
/*      '0' */ 4, 42, 39, 40, 41, 7, 7, 7, 7, 7, 2, 2, 2, 2, 2, 2, 
/*      '@' */ 2, 6, 6, 44, 43, 8, 13, 2, 12, 2, 2, 2, 2, 2, 2, 2, 
/*      'P' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 15, 2, 2, 2, 
/*      '`' */ 2, 30, 32, 31, 28, 18, 23, 34, 27, 22, 2, 33, 24, 35, 21, 29, 
/*      'p' */ 36, 2, 17, 25, 19, 20, 37, 26, 5 };

    static sbyte MapC(int code)
    { // '\0' <= code <= '\U0010FFFF'
      if (code < 121) // '\0' <= code <= 'x'
        return mapC0[code - 0];
      else // 'y' <= code <= '\U0010FFFF'
        return (sbyte)2;
    }
#endregion

    static Table[] NxS = new Table[155] {
/* NxS[   0] */ new Table(0, 0, 0, null), // Shortest string ""
/* NxS[   1] */ // Shortest string "\t"
      new Table(17, 22, -1, new short[] {30, 31, 32, 33, 34, 35, 
          36, -1, 37, 38, 39, 40, 41, -1, 42, 43, -1, 44, 45, 46, 47, 48}),
/* NxS[   2] */ // Shortest string "/"
      new Table(1, 3, -1, new short[] {20, -1, 21}),
/* NxS[   3] */ new Table(0, 0, -1, null), // Shortest string "\0"
/* NxS[   4] */ // Shortest string "0"
      new Table(39, 25, -1, new short[] {5, 5, 5, 5, -1, -1, 
          -1, -1, -1, -1, 5, 154, -1, 5, 150, -1, -1, 15, -1, -1, -1, -1, 
          -1, -1, 150}),
/* NxS[   5] */ // Shortest string "5"
      new Table(39, 25, -1, new short[] {5, 5, 5, 5, -1, -1, 
          -1, -1, -1, -1, 5, -1, -1, 5, 150, -1, -1, 15, -1, -1, -1, -1, 
          -1, -1, 150}),
/* NxS[   6] */ // Shortest string "."
      new Table(39, 14, -1, new short[] {12, 12, 12, 12, -1, -1, 
          -1, -1, -1, -1, 12, -1, -1, 12}),
/* NxS[   7] */ // Shortest string "\""
      new Table(14, 2, 146, new short[] {11, 147}),
/* NxS[   8] */ // Shortest string "\t#pragma\t"
      new Table(0, 4, 8, new short[] {-1, 8, 8, -1}),
/* NxS[   9] */ new Table(0, 0, -1, null), // Shortest string "\tin\t"
/* NxS[  10] */ new Table(0, 0, -1, null), // Shortest string "\tint\t"
/* NxS[  11] */ new Table(0, 0, -1, null), // Shortest string "\"\""
/* NxS[  12] */ // Shortest string ".0"
      new Table(39, 34, -1, new short[] {12, 12, 12, 12, -1, -1, 
          -1, -1, -1, -1, 12, -1, -1, 12, 148, -1, -1, -1, 13, 13, -1, -1, 
          -1, -1, 148, -1, -1, -1, -1, 13, -1, -1, -1, 13}),
/* NxS[  13] */ new Table(0, 0, -1, null), // Shortest string ".0H"
/* NxS[  14] */ // Shortest string ".0E0"
      new Table(39, 34, -1, new short[] {14, 14, 14, 14, -1, -1, 
          -1, -1, -1, -1, 14, -1, -1, 14, -1, -1, -1, -1, 13, 13, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, 13, -1, -1, -1, 13}),
/* NxS[  15] */ // Shortest string "0."
      new Table(39, 34, -1, new short[] {12, 12, 12, 12, -1, -1, 
          -1, -1, -1, -1, 12, -1, -1, 12, 151, -1, -1, -1, 16, 16, -1, -1, 
          -1, -1, 151, -1, -1, -1, -1, 16, -1, -1, -1, 16}),
/* NxS[  16] */ new Table(0, 0, -1, null), // Shortest string "0.H"
/* NxS[  17] */ // Shortest string "0.E0"
      new Table(39, 34, -1, new short[] {17, 17, 17, 17, -1, -1, 
          -1, -1, -1, -1, 17, -1, -1, 17, -1, -1, -1, -1, 16, 16, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, 16, -1, -1, -1, 16}),
/* NxS[  18] */ // Shortest string "0E0"
      new Table(39, 14, -1, new short[] {18, 18, 18, 18, -1, -1, 
          -1, -1, -1, -1, 18, -1, -1, 18}),
/* NxS[  19] */ // Shortest string "0x0"
      new Table(39, 39, -1, new short[] {19, 19, 19, 19, 19, 19, 
          -1, -1, -1, -1, 19, -1, 19, 19, 19, -1, -1, -1, -1, 19, -1, -1, 
          -1, -1, 19, -1, -1, -1, -1, 19, -1, -1, -1, -1, 19, -1, 19, 19, 
          19}),
/* NxS[  20] */ // Shortest string "//"
      new Table(0, 1, 20, new short[] {-1}),
/* NxS[  21] */ // Shortest string "/*"
      new Table(0, 4, 21, new short[] {-1, 21, 21, 22}),
/* NxS[  22] */ // Shortest string "/**"
      new Table(1, 3, -1, new short[] {23, -1, 22}),
/* NxS[  23] */ new Table(0, 0, -1, null), // Shortest string "/**/"
/* NxS[  24] */ // Shortest string ""
      new Table(0, 4, 26, new short[] {25, 26, 26, 27}),
/* NxS[  25] */ new Table(0, 0, -1, null), // Shortest string ""
/* NxS[  26] */ // Shortest string "/"
      new Table(0, 4, 26, new short[] {-1, 26, 26, 27}),
/* NxS[  27] */ // Shortest string "*"
      new Table(1, 3, -1, new short[] {28, -1, 27}),
/* NxS[  28] */ new Table(0, 0, -1, null), // Shortest string "*/"
/* NxS[  29] */ // Shortest string ""
      new Table(39, 23, 3, new short[] {5, 5, 5, 5, 3, 3, 
          1, 2, 3, 3, 4, 3, 3, 5, 3, 3, 3, 6, 3, 3, 7, 3, 
          1}),
/* NxS[  30] */ // Shortest string "\tr"
      new Table(18, 1, -1, new short[] {144}),
/* NxS[  31] */ // Shortest string "\te"
      new Table(5, 20, -1, new short[] {138, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 139, -1, -1, 82}),
/* NxS[  32] */ // Shortest string "\tt"
      new Table(17, 11, -1, new short[] {86, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, 137}),
/* NxS[  33] */ // Shortest string "\tu"
      new Table(25, 1, -1, new short[] {134}),
/* NxS[  34] */ // Shortest string "\tn"
      new Table(30, 1, -1, new short[] {130}),
/* NxS[  35] */ // Shortest string "\ti"
      new Table(21, 17, -1, new short[] {124, -1, 62, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 75}),
/* NxS[  36] */ // Shortest string "\tf"
      new Table(22, 9, -1, new short[] {114, -1, 115, -1, -1, -1, 
          -1, 116, 117}),
/* NxS[  37] */ // Shortest string "\ts"
      new Table(19, 12, -1, new short[] {96, -1, -1, -1, -1, -1, 
          -1, 97, -1, -1, -1, 98}),
/* NxS[  38] */ // Shortest string "\tw"
      new Table(27, 1, -1, new short[] {59}),
/* NxS[  39] */ // Shortest string "\th"
      new Table(30, 1, -1, new short[] {94}),
/* NxS[  40] */ // Shortest string "\td"
      new Table(18, 12, -1, new short[] {90, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 62}),
/* NxS[  41] */ // Shortest string "\to"
      new Table(20, 1, -1, new short[] {89}),
/* NxS[  42] */ // Shortest string "\tc"
      new Table(24, 7, -1, new short[] {80, -1, -1, -1, -1, 81, 
          82}),
/* NxS[  43] */ // Shortest string "\tb"
      new Table(17, 21, -1, new short[] {73, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, 74, -1, -1, -1, -1, -1, -1, -1, 75}),
/* NxS[  44] */ // Shortest string "\tg"
      new Table(29, 1, -1, new short[] {71}),
/* NxS[  45] */ // Shortest string "\tm"
      new Table(30, 1, -1, new short[] {69}),
/* NxS[  46] */ // Shortest string "\tp"
      new Table(20, 1, -1, new short[] {65}),
/* NxS[  47] */ // Shortest string "\tv"
      new Table(18, 12, -1, new short[] {55, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, 56}),
/* NxS[  48] */ // Shortest string "\t#"
      new Table(36, 1, -1, new short[] {49}),
/* NxS[  49] */ // Shortest string "\t#p"
      new Table(17, 1, -1, new short[] {50}),
/* NxS[  50] */ // Shortest string "\t#pr"
      new Table(30, 1, -1, new short[] {51}),
/* NxS[  51] */ // Shortest string "\t#pra"
      new Table(34, 1, -1, new short[] {52}),
/* NxS[  52] */ // Shortest string "\t#prag"
      new Table(35, 1, -1, new short[] {53}),
/* NxS[  53] */ // Shortest string "\t#pragm"
      new Table(30, 1, -1, new short[] {54}),
/* NxS[  54] */ // Shortest string "\t#pragma"
      new Table(0, 17, -1, new short[] {8, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 8}),
/* NxS[  55] */ // Shortest string "\tve"
      new Table(31, 1, -1, new short[] {63}),
/* NxS[  56] */ // Shortest string "\tvo"
      new Table(24, 1, -1, new short[] {57}),
/* NxS[  57] */ // Shortest string "\tvol"
      new Table(30, 1, -1, new short[] {58}),
/* NxS[  58] */ // Shortest string "\tvola"
      new Table(19, 1, -1, new short[] {59}),
/* NxS[  59] */ // Shortest string "\twh"
      new Table(22, 1, -1, new short[] {60}),
/* NxS[  60] */ // Shortest string "\twhi"
      new Table(24, 1, -1, new short[] {61}),
/* NxS[  61] */ // Shortest string "\tels"
      new Table(18, 1, -1, new short[] {62}),
/* NxS[  62] */ // Shortest string "\tif"
      new Table(0, 17, -1, new short[] {9, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9}),
/* NxS[  63] */ // Shortest string "\tvec"
      new Table(39, 23, -1, new short[] {64, 64, 64, -1, -1, -1, 
          10, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
          10}),
/* NxS[  64] */ // Shortest string "\tivec"
      new Table(0, 17, -1, new short[] {10, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 10}),
/* NxS[  65] */ // Shortest string "\tpu"
      new Table(32, 1, -1, new short[] {66}),
/* NxS[  66] */ // Shortest string "\tpub"
      new Table(24, 1, -1, new short[] {67}),
/* NxS[  67] */ // Shortest string "\tstat"
      new Table(22, 1, -1, new short[] {68}),
/* NxS[  68] */ // Shortest string "\tstati"
      new Table(31, 1, -1, new short[] {62}),
/* NxS[  69] */ // Shortest string "\tma"
      new Table(19, 1, -1, new short[] {70}),
/* NxS[  70] */ // Shortest string "\tmat"
      new Table(39, 3, -1, new short[] {64, 64, 64}),
/* NxS[  71] */ // Shortest string "\tgo"
      new Table(19, 1, -1, new short[] {72}),
/* NxS[  72] */ // Shortest string "\tgot"
      new Table(29, 1, -1, new short[] {62}),
/* NxS[  73] */ // Shortest string "\tbr"
      new Table(18, 1, -1, new short[] {78}),
/* NxS[  74] */ // Shortest string "\tbo"
      new Table(29, 1, -1, new short[] {77}),
/* NxS[  75] */ // Shortest string "\tiv"
      new Table(18, 1, -1, new short[] {76}),
/* NxS[  76] */ // Shortest string "\tive"
      new Table(31, 1, -1, new short[] {64}),
/* NxS[  77] */ // Shortest string "\tboo"
      new Table(24, 1, -1, new short[] {64}),
/* NxS[  78] */ // Shortest string "\tbre"
      new Table(30, 1, -1, new short[] {79}),
/* NxS[  79] */ // Shortest string "\tbrea"
      new Table(33, 1, -1, new short[] {62}),
/* NxS[  80] */ // Shortest string "\tcl"
      new Table(30, 1, -1, new short[] {87}),
/* NxS[  81] */ // Shortest string "\tco"
      new Table(21, 1, -1, new short[] {83}),
/* NxS[  82] */ // Shortest string "\tel"
      new Table(25, 1, -1, new short[] {61}),
/* NxS[  83] */ // Shortest string "\tcon"
      new Table(19, 1, -1, new short[] {84}),
/* NxS[  84] */ // Shortest string "\tcont"
      new Table(22, 1, -1, new short[] {85}),
/* NxS[  85] */ // Shortest string "\tconti"
      new Table(21, 1, -1, new short[] {86}),
/* NxS[  86] */ // Shortest string "\ttr"
      new Table(20, 1, -1, new short[] {61}),
/* NxS[  87] */ // Shortest string "\tcla"
      new Table(25, 1, -1, new short[] {88}),
/* NxS[  88] */ // Shortest string "\tthi"
      new Table(25, 1, -1, new short[] {62}),
/* NxS[  89] */ // Shortest string "\tou"
      new Table(19, 1, -1, new short[] {62}),
/* NxS[  90] */ // Shortest string "\tde"
      new Table(23, 1, -1, new short[] {91}),
/* NxS[  91] */ // Shortest string "\tdef"
      new Table(30, 1, -1, new short[] {92}),
/* NxS[  92] */ // Shortest string "\tdefa"
      new Table(20, 1, -1, new short[] {93}),
/* NxS[  93] */ // Shortest string "\tdefau"
      new Table(24, 1, -1, new short[] {89}),
/* NxS[  94] */ // Shortest string "\tha"
      new Table(24, 1, -1, new short[] {95}),
/* NxS[  95] */ // Shortest string "\thal"
      new Table(23, 1, -1, new short[] {63}),
/* NxS[  96] */ // Shortest string "\tst"
      new Table(17, 14, -1, new short[] {111, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, 112}),
/* NxS[  97] */ // Shortest string "\tsw"
      new Table(22, 1, -1, new short[] {108}),
/* NxS[  98] */ // Shortest string "\tsa"
      new Table(35, 1, -1, new short[] {99}),
/* NxS[  99] */ // Shortest string "\tsam"
      new Table(36, 1, -1, new short[] {100}),
/* NxS[ 100] */ // Shortest string "\tsamp"
      new Table(24, 1, -1, new short[] {101}),
/* NxS[ 101] */ // Shortest string "\tsampl"
      new Table(18, 1, -1, new short[] {102}),
/* NxS[ 102] */ // Shortest string "\tsample"
      new Table(17, 1, -1, new short[] {103}),
/* NxS[ 103] */ // Shortest string "\tsampler"
      new Table(39, 6, -1, new short[] {104, 104, -1, 104, -1, 105}),
/* NxS[ 104] */ // Shortest string "\tsampler2"
      new Table(43, 1, -1, new short[] {64}),
/* NxS[ 105] */ // Shortest string "\tsamplerC"
      new Table(20, 1, -1, new short[] {106}),
/* NxS[ 106] */ // Shortest string "\tsamplerCu"
      new Table(32, 1, -1, new short[] {107}),
/* NxS[ 107] */ // Shortest string "\tsamplerCub"
      new Table(18, 1, -1, new short[] {64}),
/* NxS[ 108] */ // Shortest string "\tswi"
      new Table(19, 1, -1, new short[] {109}),
/* NxS[ 109] */ // Shortest string "\tswit"
      new Table(31, 1, -1, new short[] {110}),
/* NxS[ 110] */ // Shortest string "\tswitc"
      new Table(27, 1, -1, new short[] {62}),
/* NxS[ 111] */ // Shortest string "\tstr"
      new Table(20, 1, -1, new short[] {113}),
/* NxS[ 112] */ // Shortest string "\tsta"
      new Table(19, 1, -1, new short[] {67}),
/* NxS[ 113] */ // Shortest string "\tstru"
      new Table(31, 1, -1, new short[] {89}),
/* NxS[ 114] */ // Shortest string "\tfi"
      new Table(5, 1, -1, new short[] {122}),
/* NxS[ 115] */ // Shortest string "\tfl"
      new Table(29, 1, -1, new short[] {120}),
/* NxS[ 116] */ // Shortest string "\tfo"
      new Table(17, 1, -1, new short[] {118}),
/* NxS[ 117] */ // Shortest string "\tfa"
      new Table(24, 1, -1, new short[] {82}),
/* NxS[ 118] */ // Shortest string "\tfor"
      new Table(0, 19, -1, new short[] {9, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9, -1, 119}),
/* NxS[ 119] */ // Shortest string "\tfore"
      new Table(30, 1, -1, new short[] {109}),
/* NxS[ 120] */ // Shortest string "\tflo"
      new Table(30, 1, -1, new short[] {121}),
/* NxS[ 121] */ // Shortest string "\tfloa"
      new Table(19, 1, -1, new short[] {63}),
/* NxS[ 122] */ // Shortest string "\tfix"
      new Table(18, 1, -1, new short[] {123}),
/* NxS[ 123] */ // Shortest string "\tfixe"
      new Table(28, 1, -1, new short[] {63}),
/* NxS[ 124] */ // Shortest string "\tin"
      new Table(0, 20, -1, new short[] {9, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9, -1, -1, 125}),
/* NxS[ 125] */ // Shortest string "\tint"
      new Table(0, 19, -1, new short[] {10, -1, -1, -1, -1, -1, 
          -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 10, -1, 126}),
/* NxS[ 126] */ // Shortest string "\tinte"
      new Table(17, 1, -1, new short[] {127}),
/* NxS[ 127] */ // Shortest string "\tinter"
      new Table(23, 1, -1, new short[] {128}),
/* NxS[ 128] */ // Shortest string "\tnamesp"
      new Table(30, 1, -1, new short[] {129}),
/* NxS[ 129] */ // Shortest string "\tnamespa"
      new Table(31, 1, -1, new short[] {61}),
/* NxS[ 130] */ // Shortest string "\tna"
      new Table(35, 1, -1, new short[] {131}),
/* NxS[ 131] */ // Shortest string "\tnam"
      new Table(18, 1, -1, new short[] {132}),
/* NxS[ 132] */ // Shortest string "\tname"
      new Table(25, 1, -1, new short[] {133}),
/* NxS[ 133] */ // Shortest string "\tnames"
      new Table(36, 1, -1, new short[] {128}),
/* NxS[ 134] */ // Shortest string "\tus"
      new Table(22, 1, -1, new short[] {135}),
/* NxS[ 135] */ // Shortest string "\tusi"
      new Table(21, 1, -1, new short[] {136}),
/* NxS[ 136] */ // Shortest string "\tusin"
      new Table(34, 1, -1, new short[] {62}),
/* NxS[ 137] */ // Shortest string "\tth"
      new Table(22, 1, -1, new short[] {88}),
/* NxS[ 138] */ // Shortest string "\tex"
      new Table(19, 1, -1, new short[] {141}),
/* NxS[ 139] */ // Shortest string "\ten"
      new Table(20, 1, -1, new short[] {140}),
/* NxS[ 140] */ // Shortest string "\tenu"
      new Table(35, 1, -1, new short[] {62}),
/* NxS[ 141] */ // Shortest string "\text"
      new Table(18, 1, -1, new short[] {142}),
/* NxS[ 142] */ // Shortest string "\tretu"
      new Table(17, 1, -1, new short[] {143}),
/* NxS[ 143] */ // Shortest string "\tretur"
      new Table(21, 1, -1, new short[] {62}),
/* NxS[ 144] */ // Shortest string "\tre"
      new Table(19, 1, -1, new short[] {145}),
/* NxS[ 145] */ // Shortest string "\tret"
      new Table(20, 1, -1, new short[] {142}),
/* NxS[ 146] */ // Shortest string "\"/"
      new Table(14, 2, 146, new short[] {11, 147}),
/* NxS[ 147] */ // Shortest string "\"\\"
      new Table(0, 1, 146, new short[] {-1}),
/* NxS[ 148] */ // Shortest string ".0E"
      new Table(39, 17, -1, new short[] {14, 14, 14, 14, -1, -1, 
          -1, -1, -1, -1, 14, -1, -1, 14, -1, 149, 149}),
/* NxS[ 149] */ // Shortest string ".0E+"
      new Table(39, 14, -1, new short[] {14, 14, 14, 14, -1, -1, 
          -1, -1, -1, -1, 14, -1, -1, 14}),
/* NxS[ 150] */ // Shortest string "0E"
      new Table(39, 17, -1, new short[] {18, 18, 18, 18, -1, -1, 
          -1, -1, -1, -1, 18, -1, -1, 18, -1, 153, 153}),
/* NxS[ 151] */ // Shortest string "0.E"
      new Table(39, 17, -1, new short[] {17, 17, 17, 17, -1, -1, 
          -1, -1, -1, -1, 17, -1, -1, 17, -1, 152, 152}),
/* NxS[ 152] */ // Shortest string "0.E+"
      new Table(39, 14, -1, new short[] {17, 17, 17, 17, -1, -1, 
          -1, -1, -1, -1, 17, -1, -1, 17}),
/* NxS[ 153] */ // Shortest string "0E+"
      new Table(39, 14, -1, new short[] {18, 18, 18, 18, -1, -1, 
          -1, -1, -1, -1, 18, -1, -1, 18}),
/* NxS[ 154] */ // Shortest string "0x"
      new Table(39, 39, -1, new short[] {19, 19, 19, 19, 19, 19, 
          -1, -1, -1, -1, 19, -1, 19, 19, 19, -1, -1, -1, -1, 19, -1, -1, 
          -1, -1, 19, -1, -1, -1, -1, 19, -1, -1, -1, -1, 19, -1, 19, 19, 
          19}),
    };

int NextState() {
    if (code == ScanBuff.EndOfFile)
        return eofNum;
    else
        unchecked {
            int rslt;
            int idx = MapC(code) - NxS[state].min;
            if (idx < 0) idx += 45;
            if ((uint)idx >= (uint)NxS[state].rng) rslt = NxS[state].dflt;
            else rslt = NxS[state].nxt[idx];
            return rslt;
        }
}

#endregion


#if BACKUP
        // ==============================================================
        // == Nested struct used for backup in automata that do backup ==
        // ==============================================================

        struct Context // class used for automaton backup.
        {
            public int bPos;
            public int rPos; // scanner.readPos saved value
            public int cCol;
            public int lNum; // Need this in case of backup over EOL.
            public int state;
            public int cChr;
        }
        
        private Context ctx = new Context();
#endif // BACKUP

        // ==============================================================
        // ==== Nested struct to support input switching in scanners ====
        // ==============================================================

		struct BufferContext {
            internal ScanBuff buffSv;
			internal int chrSv;
			internal int cColSv;
			internal int lNumSv;
		}

        // ==============================================================
        // ===== Private methods to save and restore buffer contexts ====
        // ==============================================================

        /// <summary>
        /// This method creates a buffer context record from
        /// the current buffer object, together with some
        /// scanner state values. 
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        BufferContext MkBuffCtx()
		{
			BufferContext rslt;
			rslt.buffSv = this.buffer;
			rslt.chrSv = this.code;
			rslt.cColSv = this.cCol;
			rslt.lNumSv = this.lNum;
			return rslt;
		}

        /// <summary>
        /// This method restores the buffer value and allied
        /// scanner state from the given context record value.
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void RestoreBuffCtx(BufferContext value)
		{
			this.buffer = value.buffSv;
			this.code = value.chrSv;
			this.cCol = value.cColSv;
			this.lNum = value.lNumSv;
        } 
        // =================== End Nested classes =======================

#if !NOFILES
     public Scanner(Stream file) {
            SetSource(file, 0); // unicode option
        }

        public Scanner(Stream file, string codepage) {
            SetSource(file, CodePageHandling.GetCodePage(codepage));
        }   
#endif // !NOFILES

     public Scanner() { }

        private int readPos;

        void GetCode()
        {
            if (code == '\n')  // This needs to be fixed for other conventions
                               // i.e. [\r\n\205\u2028\u2029]
            { 
                cCol = -1;
                lNum++;
            }
            readPos = buffer.Pos;

            // Now read new codepoint.
            code = buffer.Read();
            if (code > ScanBuff.EndOfFile)
            {
#if (!BYTEMODE)
                if (code >= 0xD800 && code <= 0xDBFF)
                {
                    int next = buffer.Read();
                    if (next < 0xDC00 || next > 0xDFFF)
                        code = ScanBuff.UnicodeReplacementChar;
                    else
                        code = (0x10000 + ((code & 0x3FF) << 10) + (next & 0x3FF));
                }
#endif
                cCol++;
            }
        }

        void MarkToken()
        {
#if (!PERSIST)
            buffer.Mark();
#endif
            tokPos = readPos;
            tokLin = lNum;
            tokCol = cCol;
        }
        
        void MarkEnd()
        {
            tokTxt = null;
            tokEPos = readPos;
            tokELin = lNum;
            tokECol = cCol;
        }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int Peek()
        {
            int rslt, codeSv = code, cColSv = cCol, lNumSv = lNum, bPosSv = buffer.Pos;
            GetCode(); rslt = code;
            lNum = lNumSv; cCol = cColSv; code = codeSv; buffer.Pos = bPosSv;
            return rslt;
        }

        // ==============================================================
        // =====    Initialization of string-based input buffers     ====
        // ==============================================================

        /// <summary>
        /// Create and initialize a StringBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the input string</param>
        /// <param name="offset">starting offset in the string</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(string source, int offset)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.buffer.Pos = offset;
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }

        // ================ LineBuffer Initialization ===================
        /// <summary>
        /// Create and initialize a LineBuff buffer object for this scanner
        /// </summary>
        /// <param name="source">the list of input strings</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(IList<string> source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            this.lNum = 0;
            GetCode();
        }

#if !NOFILES        
        // =============== StreamBuffer Initialization ==================

        /// <summary>
        /// Create and initialize a StreamBuff buffer object for this scanner.
        /// StreamBuff is buffer for 8-bit byte files.
        /// </summary>
        /// <param name="source">the input byte stream</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source)
        {
            this.buffer = ScanBuff.GetBuffer(source);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
        
#if !BYTEMODE
        // ================ TextBuffer Initialization ===================

        /// <summary>
        /// Create and initialize a TextBuff buffer object for this scanner.
        /// TextBuff is a buffer for encoded unicode files.
        /// </summary>
        /// <param name="source">the input text file</param>
        /// <param name="fallbackCodePage">Code page to use if file has
        /// no BOM. For 0, use machine default; for -1, 8-bit binary</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public void SetSource(Stream source, int fallbackCodePage)
        {
            this.buffer = ScanBuff.GetBuffer(source, fallbackCodePage);
            this.lNum = 0;
            this.code = '\n'; // to initialize yyline, yycol and lineStart
            GetCode();
        }
#endif // !BYTEMODE
#endif // !NOFILES
        
        // ==============================================================

#if BABEL
        //
        //  Get the next token for Visual Studio
        //
        //  "state" is the inout mode variable that maintains scanner
        //  state between calls, using the EolState property. In principle,
        //  if the calls of EolState are costly set could be called once
        //  only per line, at the start; and get called only at the end
        //  of the line. This needs more infrastructure ...
        //
        public int GetNext(ref int state, out int start, out int end)
        {
                Tokens next;
            int s, e;
            s = state;        // state at start
            EolState = state;
                next = (Tokens)Scan();
            state = EolState;
            e = state;       // state at end;
            start = tokPos;
            end = tokEPos - 1; // end is the index of last char.
            return (int)next;
        }        
#endif // BABEL

        // ======== AbstractScanner<> Implementation =========

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yylex")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yylex")]
        public override int yylex()
        {
            // parserMax is set by reflecting on the Tokens
            // enumeration.  If maxParseToken is defined
            // that is used, otherwise int.MaxValue is used.
            int next;
            do { next = Scan(); } while (next >= parserMax);
            return next;
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yypos { get { return tokPos; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yyline { get { return tokLin; } }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        int yycol { get { return tokCol; } }

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yytext")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yytext")]
        public string yytext
        {
            get 
            {
                if (tokTxt == null) 
                    tokTxt = buffer.GetString(tokPos, tokEPos);
                return tokTxt;
            }
        }

        /// <summary>
        /// Discards all but the first "n" codepoints in the recognized pattern.
        /// Resets the buffer position so that only n codepoints have been consumed;
        /// yytext is also re-evaluated. 
        /// </summary>
        /// <param name="n">The number of codepoints to consume</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void yyless(int n)
        {
            buffer.Pos = tokPos;
            // Must read at least one char, so set before start.
            cCol = tokCol - 1; 
            GetCode();
            // Now ensure that line counting is correct.
            lNum = tokLin;
            // And count the rest of the text.
            for (int i = 0; i < n; i++) GetCode();
            MarkEnd();
        }
       
        //
        //  It would be nice to count backward in the text
        //  but it does not seem possible to re-establish
        //  the correct column counts except by going forward.
        //
        /// <summary>
        /// Removes the last "n" code points from the pattern.
        /// </summary>
        /// <param name="n">The number to remove</param>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        void _yytrunc(int n) { yyless(yyleng - n); }
        
        //
        // This is painful, but we no longer count
        // codepoints.  For the overwhelming majority 
        // of cases the single line code is fast, for
        // the others, well, at least it is all in the
        // buffer so no files are touched. Note that we
        // can't use (tokEPos - tokPos) because of the
        // possibility of surrogate pairs in the token.
        //
        /// <summary>
        /// The length of the pattern in codepoints (not the same as 
        /// string-length if the pattern contains any surrogate pairs).
        /// </summary>
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "yyleng")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "yyleng")]
        public int yyleng
        {
            get {
                if (tokELin == tokLin)
                    return tokECol - tokCol;
                else
#if BYTEMODE
                    return tokEPos - tokPos;
#else
                {
                    int ch;
                    int count = 0;
                    int save = buffer.Pos;
                    buffer.Pos = tokPos;
                    do {
                        ch = buffer.Read();
                        if (!char.IsHighSurrogate((char)ch)) count++;
                    } while (buffer.Pos < tokEPos && ch != ScanBuff.EndOfFile);
                    buffer.Pos = save;
                    return count;
                }
#endif // BYTEMODE
            }
        }
        
        // ============ methods available in actions ==============

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int YY_START {
            get { return currentScOrd; }
            set { currentScOrd = value; 
                  currentStart = startState[value]; 
            } 
        }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void BEGIN(int next) {
            currentScOrd = next;
            currentStart = startState[next];
        }

        // ============== The main tokenizer code =================

        int Scan() {
                for (; ; ) {
                    int next;              // next state to enter
#if LEFTANCHORS
                    for (;;) {
                        // Discard characters that do not start any pattern.
                        // Must check the left anchor condition after *every* GetCode!
                        state = ((cCol == 0) ? anchorState[currentScOrd] : currentStart);
                        if ((next = NextState()) != goStart) break; // LOOP EXIT HERE...
                        GetCode();
                    }
                    
#else // !LEFTANCHORS
                    state = currentStart;
                    while ((next = NextState()) == goStart) {
                        // At this point, the current character has no
                        // transition from the current state.  We discard 
                        // the "no-match" char.   In traditional LEX such 
                        // characters are echoed to the console.
                        GetCode();
                    }
#endif // LEFTANCHORS                    
                    // At last, a valid transition ...    
                    MarkToken();
                    state = next;
                    GetCode();                    
#if BACKUP
                    bool contextSaved = false;
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                        if (state <= maxAccept && next > maxAccept) { // need to prepare backup data
                            // Store data for the *latest* accept state that was found.
                            SaveStateAndPos( ref ctx );
                            contextSaved = true;
                        }
                        state = next;
                        GetCode();
                    }
                    if (state > maxAccept && contextSaved)
                        RestoreStateAndPos( ref ctx );
#else  // BACKUP
                    while ((next = NextState()) > eofNum) { // Exit for goStart AND for eofNum
                         state = next;
                         GetCode();
                    }
#endif // BACKUP
                    if (state <= maxAccept) {
                        MarkEnd();
#region ActionSwitch
#pragma warning disable 162, 1522
    switch (state)
    {
        case eofNum:
            if (yywrap())
                return (int)Tokens.EOF;
            break;
        case 1: // Recognized '{white_space}',	Shortest string "\t"
/* Ignore */
            break;
        case 2: // Recognized '.',	Shortest string "/"
        case 3: // Recognized '.',	Shortest string "\0"
        case 6: // Recognized '.',	Shortest string "."
        case 7: // Recognized '.',	Shortest string "\""
return (int)ShaderlabToken.UNDEFINED;
            break;
        case 4: // Recognized '{digit}+',	Shortest string "0"
        case 5: // Recognized '{digit}+',	Shortest string "5"
return (int)ShaderlabToken.NUMBER;
            break;
        case 8: // Recognized '{white_space}{unitykeywords}{white_space}{words}',	Shortest string "\t#pragma\t"
return (int)ShaderlabToken.KEYWORD;
            break;
        case 9: // Recognized '{white_space}{keyword}{white_space}',	Shortest string "\tin\t"
return (int)ShaderlabToken.KEYWORD;
            break;
        case 10: // Recognized '{white_space}{datatype}{white_space}',	Shortest string "\tint\t"
return (int)ShaderlabToken.DATATYPE;
            break;
        case 11: // Recognized '\"(\\.|[^\\"])*\"',	Shortest string "\"\""
return (int)ShaderlabToken.STRING_LITERAL;
            break;
        case 12: // Recognized '{digit}*"."{digit}+({exponent})?({floatsuffix})?',	Shortest string ".0"
        case 13: // Recognized '{digit}*"."{digit}+({exponent})?({floatsuffix})?',	Shortest string ".0H"
        case 14: // Recognized '{digit}*"."{digit}+({exponent})?({floatsuffix})?',	Shortest string ".0E0"
return (int)ShaderlabToken.FLOAT;
            break;
        case 15: // Recognized '{digit}+"."{digit}*({exponent})?({floatsuffix})?',	Shortest string "0."
        case 16: // Recognized '{digit}+"."{digit}*({exponent})?({floatsuffix})?',	Shortest string "0.H"
        case 17: // Recognized '{digit}+"."{digit}*({exponent})?({floatsuffix})?',	Shortest string "0.E0"
return (int)ShaderlabToken.FLOAT;
            break;
        case 18: // Recognized '{digit}+{exponent}',	Shortest string "0E0"
return (int)ShaderlabToken.FLOAT;
            break;
        case 19: // Recognized '"0x"{hexdigit}+',	Shortest string "0x0"
return (int)ShaderlabToken.NUMBER;
            break;
        case 20: // Recognized '"//"(.)*',	Shortest string "//"
return (int)ShaderlabToken.COMMENT_LINE;
            break;
        case 21: // Recognized '{CmntStart}{words}\**',	Shortest string "/*"
        case 22: // Recognized '{CmntStart}{words}\**',	Shortest string "/**"
BEGIN(COMMENT); return (int)ShaderlabToken.COMMENT;
            break;
        case 23: // Recognized '{CmntStart}{words}\**{CmntEnd}',	Shortest string "/**/"
return (int)ShaderlabToken.COMMENT;
            break;
        case 24: // In <COMMENT> Recognized '{words}\**',	Shortest string ""
        case 25: // In <COMMENT> Recognized '\n',	Shortest string ""
        case 26: // In <COMMENT> Recognized '{words}\**',	Shortest string "/"
        case 27: // In <COMMENT> Recognized '{words}\**',	Shortest string "*"
return (int)ShaderlabToken.COMMENT;
            break;
        case 28: // In <COMMENT> Recognized '{words}\**{CmntEnd}',	Shortest string "*/"
BEGIN(INITIAL); return (int)ShaderlabToken.COMMENT;
            break;
        default:
            break;
    }
#pragma warning restore 162, 1522
#endregion
                    }
                }
        }

#if BACKUP
        void SaveStateAndPos(ref Context ctx) {
            ctx.bPos  = buffer.Pos;
            ctx.rPos  = readPos;
            ctx.cCol  = cCol;
            ctx.lNum  = lNum;
            ctx.state = state;
            ctx.cChr  = code;
        }

        void RestoreStateAndPos(ref Context ctx) {
            buffer.Pos = ctx.bPos;
            readPos = ctx.rPos;
            cCol  = ctx.cCol;
            lNum  = ctx.lNum;
            state = ctx.state;
            code  = ctx.cChr;
        }
#endif  // BACKUP

        // ============= End of the tokenizer code ================

#if STACK        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void yy_clear_stack() { scStack.Clear(); }
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal int yy_top_state() { return scStack.Peek(); }
        
        internal void yy_push_state(int state)
        {
            scStack.Push(currentScOrd);
            BEGIN(state);
        }
        
        internal void yy_pop_state()
        {
            // Protect against input errors that pop too far ...
            if (scStack.Count > 0) {
				int newSc = scStack.Pop();
				BEGIN(newSc);
            } // Otherwise leave stack unchanged.
        }
 #endif // STACK

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal void ECHO() { Console.Out.Write(yytext); }
        
    } // end class $Scanner

// ==============================================================
// <auto-generated>
// This code automatically produced from an embedded resource.
// Do not edit this file, or it will become incompatible with 
// the specification from which it was generated.
// </auto-generated>
// ==============================================================

// Code copied from GPLEX embedded resource
    [Serializable]
    public class BufferException : Exception
    {
        public BufferException() { }
        public BufferException(string message) : base(message) { }
        public BufferException(string message, Exception innerException)
            : base(message, innerException) { }
        protected BufferException(SerializationInfo info, StreamingContext context)
            : base(info, context) { }
    }

    public abstract class ScanBuff
    {
        private string fileNm;

        public const int EndOfFile = -1;
        public const int UnicodeReplacementChar = 0xFFFD;

        public bool IsFile { get { return (fileNm != null); } }
        public string FileName { get { return fileNm; } set { fileNm = value; } }

        public abstract int Pos { get; set; }
        public abstract int Read();
        public virtual void Mark() { }

        public abstract string GetString(int begin, int limit);

        public static ScanBuff GetBuffer(string source)
        {
            return new StringBuffer(source);
        }

        public static ScanBuff GetBuffer(IList<string> source)
        {
            return new LineBuffer(source);
        }

#if (!NOFILES)
        public static ScanBuff GetBuffer(Stream source)
        {
            return new BuildBuffer(source);
        }

#if (!BYTEMODE)
        public static ScanBuff GetBuffer(Stream source, int fallbackCodePage)
        {
            return new BuildBuffer(source, fallbackCodePage);
        }
#endif // !BYTEMODE
#endif // !NOFILES
    }

    #region Buffer classes

    // ==============================================================
    // =====  Definitions for various ScanBuff derived classes   ====
    // ==============================================================
    // ===============         String input          ================
    // ==============================================================

    /// <summary>
    /// This class reads characters from a single string as
    /// required, for example, by Visual Studio language services
    /// </summary>
    sealed class StringBuffer : ScanBuff
    {
        string str;        // input buffer
        int bPos;          // current position in buffer
        int sLen;

        public StringBuffer(string source)
        {
            this.str = source;
            this.sLen = source.Length;
            this.FileName = null;
        }

        public override int Read()
        {
            if (bPos < sLen) return str[bPos++];
            else if (bPos == sLen) { bPos++; return '\n'; }   // one strike, see new line
            else { bPos++; return EndOfFile; }                // two strikes and you're out!
        }

        public override string GetString(int begin, int limit)
        {
            //  "limit" can be greater than sLen with the BABEL
            //  option set.  Read returns a "virtual" EOL if
            //  an attempt is made to read past the end of the
            //  string buffer.  Without the guard any attempt 
            //  to fetch yytext for a token that includes the 
            //  EOL will throw an index exception.
            if (limit > sLen) limit = sLen;
            if (limit <= begin) return "";
            else return str.Substring(begin, limit - begin);
        }

        public override int Pos
        {
            get { return bPos; }
            set { bPos = value; }
        }

        public override string ToString() { return "StringBuffer"; }
    }

    // ==============================================================
    //  The LineBuff class contributed by Nigel Horspool, 
    //  nigelh@cs.uvic.cs
    // ==============================================================

    sealed class LineBuffer : ScanBuff
    {
        IList<string> line;    // list of source lines from a file
        int numLines;          // number of strings in line list
        string curLine;        // current line in that list
        int cLine;             // index of current line in the list
        int curLen;            // length of current line
        int curLineStart;      // position of line start in whole file
        int curLineEnd;        // position of line end in whole file
        int maxPos;            // max position ever visited in whole file
        int cPos;              // ordinal number of code in source

        // Constructed from a list of strings, one per source line.
        // The lines have had trailing '\n' characters removed.
        public LineBuffer(IList<string> lineList)
        {
            line = lineList;
            numLines = line.Count;
            cPos = curLineStart = 0;
            curLine = (numLines > 0 ? line[0] : "");
            maxPos = curLineEnd = curLen = curLine.Length;
            cLine = 1;
            FileName = null;
        }

        public override int Read()
        {
            if (cPos < curLineEnd)
                return curLine[cPos++ - curLineStart];
            if (cPos++ == curLineEnd)
                return '\n';
            if (cLine >= numLines)
                return EndOfFile;
            curLine = line[cLine];
            curLen = curLine.Length;
            curLineStart = curLineEnd + 1;
            curLineEnd = curLineStart + curLen;
            if (curLineEnd > maxPos)
                maxPos = curLineEnd;
            cLine++;
            return curLen > 0 ? curLine[0] : '\n';
        }

        // To speed up searches for the line containing a position
        private int cachedPosition;
        private int cachedIxdex;
        private int cachedLineStart;

        // Given a position pos within the entire source, the results are
        //   ix     -- the index of the containing line
        //   lstart -- the position of the first character on that line
        private void findIndex(int pos, out int ix, out int lstart)
        {
            if (pos >= cachedPosition)
            {
                ix = cachedIxdex; lstart = cachedLineStart;
            }
            else
            {
                ix = lstart = 0;
            }
            while (ix < numLines)
            {
                int len = line[ix].Length + 1;
                if (pos < lstart + len) break;
                lstart += len;
                ix++;
            }
            cachedPosition = pos;
            cachedIxdex = ix;
            cachedLineStart = lstart;
        }

        public override string GetString(int begin, int limit)
        {
            if (begin >= maxPos || limit <= begin) return "";
            int endIx, begIx, endLineStart, begLineStart;
            findIndex(begin, out begIx, out begLineStart);
            int begCol = begin - begLineStart;
            findIndex(limit, out endIx, out endLineStart);
            int endCol = limit - endLineStart;
            string s = line[begIx];
            if (begIx == endIx)
            {
                // the usual case, substring all on one line
                return (endCol <= s.Length) ?
                    s.Substring(begCol, endCol - begCol)
                    : s.Substring(begCol) + "\n";
            }
            // the string spans multiple lines, yuk!
            StringBuilder sb = new StringBuilder();
            if (begCol < s.Length)
                sb.Append(s.Substring(begCol));
            for (; ; )
            {
                sb.Append("\n");
                s = line[++begIx];
                if (begIx >= endIx) break;
                sb.Append(s);
            }
            if (endCol <= s.Length)
            {
                sb.Append(s.Substring(0, endCol));
            }
            else
            {
                sb.Append(s);
                sb.Append("\n");
            }
            return sb.ToString();
        }

        public override int Pos
        {
            get { return cPos; }
            set
            {
                cPos = value;
                findIndex(cPos, out cLine, out curLineStart);
                // cLine should be the *next* line after curLine.
                curLine = (cLine < numLines ? line[cLine++] : "");
                curLineEnd = curLineStart + curLine.Length;
            }
        }

        public override string ToString() { return "LineBuffer"; }
    }

#if (!NOFILES)
    // ==============================================================
    // =====     class BuildBuff : for unicode text files    ========
    // ==============================================================

    class BuildBuffer : ScanBuff
    {
        // Double buffer for char stream.
        class BufferElement
        {
            StringBuilder bldr = new StringBuilder();
            StringBuilder next = new StringBuilder();
            int minIx;
            int maxIx;
            int brkIx;
            bool appendToNext;

            internal BufferElement() { }

            internal int MaxIndex { get { return maxIx; } }
            // internal int MinIndex { get { return minIx; } }

            internal char this[int index]
            {
                get
                {
                    if (index < minIx || index >= maxIx)
                        throw new BufferException("Index was outside data buffer");
                    else if (index < brkIx)
                        return bldr[index - minIx];
                    else
                        return next[index - brkIx];
                }
            }

            internal void Append(char[] block, int count)
            {
                maxIx += count;
                if (appendToNext)
                    this.next.Append(block, 0, count);
                else
                {
                    this.bldr.Append(block, 0, count);
                    brkIx = maxIx;
                    appendToNext = true;
                }
            }

            internal string GetString(int start, int limit)
            {
                if (limit <= start)
                    return "";
                if (start >= minIx && limit <= maxIx)
                    if (limit < brkIx) // String entirely in bldr builder
                        return bldr.ToString(start - minIx, limit - start);
                    else if (start >= brkIx) // String entirely in next builder
                        return next.ToString(start - brkIx, limit - start);
                    else // Must do a string-concatenation
                        return
                            bldr.ToString(start - minIx, brkIx - start) +
                            next.ToString(0, limit - brkIx);
                else
                    throw new BufferException("String was outside data buffer");
            }

            internal void Mark(int limit)
            {
                if (limit > brkIx + 16) // Rotate blocks
                {
                    StringBuilder temp = bldr;
                    bldr = next;
                    next = temp;
                    next.Length = 0;
                    minIx = brkIx;
                    brkIx = maxIx;
                }
            }
        }

        BufferElement data = new BufferElement();

        int bPos;            // Postion index in the StringBuilder
        BlockReader NextBlk; // Delegate that serves char-arrays;

        private string EncodingName
        {
            get
            {
                StreamReader rdr = NextBlk.Target as StreamReader;
                return (rdr == null ? "raw-bytes" : rdr.CurrentEncoding.BodyName);
            }
        }

        public BuildBuffer(Stream stream)
        {
            FileStream fStrm = (stream as FileStream);
            if (fStrm != null) FileName = fStrm.Name;
            NextBlk = BlockReaderFactory.Raw(stream);
        }

#if (!BYTEMODE)
        public BuildBuffer(Stream stream, int fallbackCodePage)
        {
            FileStream fStrm = (stream as FileStream);
            if (fStrm != null) FileName = fStrm.Name;
            NextBlk = BlockReaderFactory.Get(stream, fallbackCodePage);
        }
#endif

        /// <summary>
        /// Marks a conservative lower bound for the buffer,
        /// allowing space to be reclaimed.  If an application 
        /// needs to call GetString at arbitrary past locations 
        /// in the input stream, Mark() is not called.
        /// </summary>
        public override void Mark() { data.Mark(bPos - 2); }

        public override int Pos
        {
            get { return bPos; }
            set { bPos = value; }
        }


        /// <summary>
        /// Read returns the ordinal number of the next char, or 
        /// EOF (-1) for an end of stream.  Note that the next
        /// code point may require *two* calls of Read().
        /// </summary>
        /// <returns></returns>
        public override int Read()
        {
            //
            //  Characters at positions 
            //  [data.offset, data.offset + data.bldr.Length)
            //  are available in data.bldr.
            //
            if (bPos < data.MaxIndex)
            {
                // ch0 cannot be EOF
                return (int)data[bPos++];
            }
            else // Read from underlying stream
            {
                // Experimental code, blocks of page size
                char[] chrs = new char[4096];
                int count = NextBlk(chrs, 0, 4096);
                if (count == 0)
                    return EndOfFile;
                else
                {
                    data.Append(chrs, count);
                    return (int)data[bPos++];
                }
            }
        }

        public override string GetString(int begin, int limit)
        {
            return data.GetString(begin, limit);
        }

        public override string ToString()
        {
            return "StringBuilder buffer, encoding: " + this.EncodingName;
        }
    }

    // =============== End ScanBuff-derived classes ==================

    public delegate int BlockReader(char[] block, int index, int number);

    // A delegate factory, serving up a delegate that
    // reads a block of characters from the underlying
    // encoded stream, via a StreamReader object.
    //
    public static class BlockReaderFactory
    {
        public static BlockReader Raw(Stream stream)
        {
            return delegate(char[] block, int index, int number)
            {
                byte[] b = new byte[number];
                int count = stream.Read(b, 0, number);
                int i = 0;
                int j = index;
                for (; i < count; i++, j++)
                    block[j] = (char)b[i];
                return count;
            };
        }

#if (!BYTEMODE)
        public static BlockReader Get(Stream stream, int fallbackCodePage)
        {
            Encoding encoding;
            int preamble = Preamble(stream);

            if (preamble != 0)  // There is a valid BOM here!
                encoding = Encoding.GetEncoding(preamble);
            else if (fallbackCodePage == -1) // Fallback is "raw" bytes
                return Raw(stream);
            else if (fallbackCodePage != -2) // Anything but "guess"
                encoding = Encoding.GetEncoding(fallbackCodePage);
            else // This is the "guess" option
            {
                int guess = new Guesser(stream).GuessCodePage();
                stream.Seek(0, SeekOrigin.Begin);
                if (guess == -1) // ==> this is a 7-bit file
                    encoding = Encoding.ASCII;
                else if (guess == 65001)
                    encoding = Encoding.UTF8;
                else             // ==> use the machine default
                    encoding = Encoding.Default;
            }
            StreamReader reader = new StreamReader(stream, encoding);
            return reader.Read;
        }

        static int Preamble(Stream stream)
        {
            int b0 = stream.ReadByte();
            int b1 = stream.ReadByte();

            if (b0 == 0xfe && b1 == 0xff)
                return 1201; // UTF16BE
            if (b0 == 0xff && b1 == 0xfe)
                return 1200; // UTF16LE

            int b2 = stream.ReadByte();
            if (b0 == 0xef && b1 == 0xbb && b2 == 0xbf)
                return 65001; // UTF8
            //
            // There is no unicode preamble, so we
            // return denoter for the machine default.
            //
            stream.Seek(0, SeekOrigin.Begin);
            return 0;
        }
#endif // !BYTEMODE
    }
#endif // !NOFILES
    #endregion Buffer classes

    // ==============================================================
    // ============      class CodePageHandling         =============
    // ==============================================================
#if (!NOFILES)
    public static class CodePageHandling
    {
        public static int GetCodePage(string option)
        {
            string command = option.ToUpperInvariant();
            if (command.StartsWith("CodePage:", StringComparison.OrdinalIgnoreCase))
                command = command.Substring(9);
            try
            {
                if (command.Equals("RAW"))
                    return -1;
                else if (command.Equals("GUESS"))
                    return -2;
                else if (command.Equals("DEFAULT"))
                    return 0;
                else if (char.IsDigit(command[0]))
                    return int.Parse(command, CultureInfo.InvariantCulture);
                else
                {
                    Encoding enc = Encoding.GetEncoding(command);
                    return enc.CodePage;
                }
            }
            catch (FormatException)
            {
                Console.Error.WriteLine(
                    "Invalid format \"{0}\", using machine default", option);
            }
            catch (ArgumentException)
            {
                Console.Error.WriteLine(
                    "Unknown code page \"{0}\", using machine default", option);
            }
            return 0;
        }
    }
#region guesser
#if (!BYTEMODE)
    // ==============================================================
    // ============          Encoding Guesser           =============
    // ==============================================================

    /// <summary>
    /// This class provides a simple finite state automaton that
    /// scans the file looking for (1) valid UTF-8 byte patterns,
    /// (2) bytes >= 0x80 which are not part of a UTF-8 sequence.
    /// The method then guesses whether it is UTF-8 or maybe some 
    /// local machine default encoding.  This works well for the
    /// various Latin encodings.
    /// </summary>
    internal class Guesser
    {
        ScanBuff buffer;

        public int GuessCodePage() { return Scan(); }

        const int maxAccept = 10;
        const int initial = 0;
        const int eofNum = 0;
        const int goStart = -1;
        const int INITIAL = 0;
        const int EndToken = 0;

        #region user code
        /* 
         *  Reads the bytes of a file to determine if it is 
         *  UTF-8 or a single-byte code page file.
         */
        public long utfX;
        public long uppr;
        #endregion user code

        int state;
        int currentStart = startState[0];
        int code;

        #region ScannerTables
        static int[] startState = new int[] { 11, 0 };

        #region CharacterMap
        static sbyte[] map = new sbyte[256] {
/*     '\0' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*   '\x10' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*   '\x20' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      '0' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      '@' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      'P' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      '`' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*      'p' */ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
/*   '\x80' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\x90' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\xA0' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\xB0' */ 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
/*   '\xC0' */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
/*   '\xD0' */ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
/*   '\xE0' */ 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
/*   '\xF0' */ 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5 };
        #endregion

        static sbyte[][] nextState = new sbyte[][] {
            new sbyte[] {0, 0, 0, 0, 0, 0},
            new sbyte[] {-1, -1, 10, -1, -1, -1},
            new sbyte[] {-1, -1, -1, -1, -1, -1},
            new sbyte[] {-1, -1, 8, -1, -1, -1},
            new sbyte[] {-1, -1, 5, -1, -1, -1},
            new sbyte[] {-1, -1, 6, -1, -1, -1},
            new sbyte[] {-1, -1, 7, -1, -1, -1},
            null,
            new sbyte[] {-1, -1, 9, -1, -1, -1},
            null,
            null,
            new sbyte[] {-1, 1, 2, 3, 4, 2}
        };


        [SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
        // Reason for suppression: cannot have self-reference in array initializer.
        static Guesser()
        {
            nextState[7] = nextState[2];
            nextState[9] = nextState[2];
            nextState[10] = nextState[2];
        }

        int NextState()
        {
            if (code == ScanBuff.EndOfFile)
                return eofNum;
            else
                return nextState[state][map[code]];
        }
        #endregion

        public Guesser(System.IO.Stream file) { SetSource(file); }

        public void SetSource(System.IO.Stream source)
        {
            this.buffer = new BuildBuffer(source);
            code = buffer.Read();
        }

        int Scan()
        {
            for (; ; )
            {
                int next;
                state = currentStart;
                while ((next = NextState()) == goStart)
                    code = buffer.Read();

                state = next;
                code = buffer.Read();

                while ((next = NextState()) > eofNum)
                {
                    state = next;
                    code = buffer.Read();
                }
                if (state <= maxAccept)
                {
                    #region ActionSwitch
#pragma warning disable 162
                    switch (state)
                    {
                        case eofNum:
                            switch (currentStart)
                            {
                                case 11:
                                    if (utfX == 0 && uppr == 0) return -1; /* raw ascii */
                                    else if (uppr * 10 > utfX) return 0;   /* default code page */
                                    else return 65001;                     /* UTF-8 encoding */
                                    break;
                            }
                            return EndToken;
                        case 1: // Recognized '{Upper128}',	Shortest string "\xC0"
                        case 2: // Recognized '{Upper128}',	Shortest string "\x80"
                        case 3: // Recognized '{Upper128}',	Shortest string "\xE0"
                        case 4: // Recognized '{Upper128}',	Shortest string "\xF0"
                            uppr++;
                            break;
                        case 5: // Recognized '{Utf8pfx4}{Utf8cont}',	Shortest string "\xF0\x80"
                            uppr += 2;
                            break;
                        case 6: // Recognized '{Utf8pfx4}{Utf8cont}{2}',	Shortest string "\xF0\x80\x80"
                            uppr += 3;
                            break;
                        case 7: // Recognized '{Utf8pfx4}{Utf8cont}{3}',	Shortest string "\xF0\x80\x80\x80"
                            utfX += 3;
                            break;
                        case 8: // Recognized '{Utf8pfx3}{Utf8cont}',	Shortest string "\xE0\x80"
                            uppr += 2;
                            break;
                        case 9: // Recognized '{Utf8pfx3}{Utf8cont}{2}',	Shortest string "\xE0\x80\x80"
                            utfX += 2;
                            break;
                        case 10: // Recognized '{Utf8pfx2}{Utf8cont}',	Shortest string "\xC0\x80"
                            utfX++;
                            break;
                        default:
                            break;
                    }
#pragma warning restore 162
                    #endregion
                }
            }
        }
    } // end class Guesser
    
#endif // !BYTEMODE
#endregion
#endif // !NOFILES

// End of code copied from embedded resource

} // end namespace
